spring:
  application:
    name: address_service
  datasource:
    username: pass
    password: 1212
    url: jdbc:postgresql://localhost:5432/useraddressdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8802

kafka:
  host: localhost:9092
  topics:
    user-created:
      topics: user_service.user_created.1
      consumerGroups: ${spring.application.name}-user-created-consumer
      replicationFactor: 1
      retentionInMs: 604800000